/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package YANG2JAVA;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int LETTER = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int String1 = 35;
  /** RegularExpression Id. */
  int number = 36;
  /** RegularExpression Id. */
  int Date = 37;
  /** RegularExpression Id. */
  int String = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"module\"",
    "\"namespace\"",
    "\"prefix\"",
    "\"typedef\"",
    "\"container\"",
    "\"list\"",
    "\"leaf\"",
    "\"import\"",
    "\"description\"",
    "\"key\"",
    "\"config\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"true\"",
    "\"false\"",
    "\"units\"",
    "\"type\"",
    "\":\"",
    "\"unit16\"",
    "\"mandatory\"",
    "\"default\"",
    "\"string\"",
    "\"organization\"",
    "\"revision\"",
    "\" max-elements\"",
    "\"leaf-list\"",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<String1>",
    "<number>",
    "<Date>",
    "<String>",
    "\"\\tdescription\"",
  };

}
