/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTokenManager.java */
package YANG2JAVA;

/** Token Manager. */
public class SyntaxCheckerTokenManager implements SyntaxCheckerConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xbf78ffe0L) != 0L)
         {
            jjmatchedKind = 32;
            return 26;
         }
         return -1;
      case 1:
         if ((active0 & 0xbf78ffe0L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 1;
            return 26;
         }
         return -1;
      case 2:
         if ((active0 & 0x4000L) != 0L)
            return 26;
         if ((active0 & 0xbf78bfe0L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 2;
            return 26;
         }
         return -1;
      case 3:
         if ((active0 & 0x3f30b2e0L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 32;
               jjmatchedPos = 3;
            }
            return 26;
         }
         if ((active0 & 0x80480d00L) != 0L)
            return 26;
         return -1;
      case 4:
         if ((active0 & 0x300000L) != 0L)
            return 26;
         if ((active0 & 0xbf00b3e0L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 4;
            return 26;
         }
         return -1;
      case 5:
         if ((active0 & 0xb6002340L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 5;
            return 26;
         }
         if ((active0 & 0x90090a0L) != 0L)
            return 26;
         return -1;
      case 6:
         if ((active0 & 0xb2002240L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 6;
            return 26;
         }
         if ((active0 & 0x4000100L) != 0L)
            return 26;
         return -1;
      case 7:
         if ((active0 & 0x20000000L) != 0L)
            return 26;
         if ((active0 & 0x92002240L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 7;
            return 26;
         }
         return -1;
      case 8:
         if ((active0 & 0x10002000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 8;
            return 26;
         }
         if ((active0 & 0x82000240L) != 0L)
            return 26;
         return -1;
      case 9:
         if ((active0 & 0x10002000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 9;
            return 26;
         }
         return -1;
      case 10:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 10;
            return 26;
         }
         if ((active0 & 0x2000L) != 0L)
            return 26;
         return -1;
      case 11:
         if ((active0 & 0x10000000L) != 0L)
            return 26;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 32:
         jjmatchedKind = 1;
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 58:
         return jjStopAtPos(0, 23);
      case 59:
         return jjStopAtPos(0, 16);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x8200L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4002000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 107:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x80000c00L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x2000020L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x480100L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x1200000L);
      case 123:
         return jjStopAtPos(0, 17);
      case 125:
         return jjStopAtPos(0, 18);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2100040L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xa4006800L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x40001000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1200000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x8220L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x10080080L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x400100L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000800L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000080L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1200000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2008200L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x401100L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2400L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 121:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 14, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 26);
         else if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x140L);
      case 102:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x80008080L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x28000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000100000L);
      case 116:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 26);
         return jjMoveStringLiteralDfa4_0(active0, 0x1200200L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 120:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000L);
      case 49:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000200L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x100L);
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 20, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8080L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x18000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000L);
      case 115:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 26);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000040L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 54:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 26);
         break;
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000100L);
      case 103:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 26);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x30002200L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x84000000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 116:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 120:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 7, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L);
      case 102:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 8, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8080000000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x22000000L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 26);
         break;
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x40L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000200L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 29, 26);
         break;
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 6, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000L);
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L);
      case 114:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(8, 9, 26);
         break;
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(8, 31, 26);
         return jjMoveStringLiteralDfa9_0(active0, 0x8010000000L);
      case 121:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(8, 25, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x8010000000L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(10, 13, 26);
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000L);
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x8010000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(11, 28, 26);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(11, 39);
         break;
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(12, 30);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 26;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 26:
                  if ((0x7ffe00000000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                     jjCheckNAddTwoStates(1, 3);
                  }
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(3, 6);
                  break;
               case 1:
                  if ((0x7ffe00000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 2:
                  if (curChar != 47)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 3:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 34)
                     jjCheckNAddStates(3, 6);
                  break;
               case 6:
                  if ((0x7ffe00000000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 7:
                  if (curChar == 47)
                     jjCheckNAddStates(7, 9);
                  break;
               case 8:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(5, 10);
                  break;
               case 10:
                  if (curChar == 34 && kind > 35)
                     kind = 35;
                  break;
               case 11:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 13:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 14:
                  if (curChar == 34 && kind > 38)
                     kind = 38;
                  break;
               case 15:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(13, 16);
                  break;
               case 16:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 17:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  jjCheckNAddStates(0, 2);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(21, 22);
                  break;
               case 22:
                  if (curChar == 45)
                     jjCheckNAdd(23);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 24:
                  if (curChar == 45)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  jjCheckNAdd(25);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 26:
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(1, 3);
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 6:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 11:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 12:
                  if (curChar == 92)
                     jjAddStates(17, 19);
                  break;
               case 13:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(10, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 26 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   20, 21, 22, 5, 11, 12, 14, 6, 8, 9, 11, 12, 14, 11, 12, 16, 
   14, 13, 15, 17, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\155\157\144\165\154\145", 
"\156\141\155\145\163\160\141\143\145", "\160\162\145\146\151\170", "\164\171\160\145\144\145\146", 
"\143\157\156\164\141\151\156\145\162", "\154\151\163\164", "\154\145\141\146", "\151\155\160\157\162\164", 
"\144\145\163\143\162\151\160\164\151\157\156", "\153\145\171", "\143\157\156\146\151\147", "\73", "\173", "\175", 
"\164\162\165\145", "\146\141\154\163\145", "\165\156\151\164\163", "\164\171\160\145", "\72", 
"\165\156\151\164\61\66", "\155\141\156\144\141\164\157\162\171", "\144\145\146\141\165\154\164", 
"\163\164\162\151\156\147", "\157\162\147\141\156\151\172\141\164\151\157\156", 
"\162\145\166\151\163\151\157\156", "\40\155\141\170\55\145\154\145\155\145\156\164\163", 
"\154\145\141\146\55\154\151\163\164", null, null, null, null, null, null, null, 
"\11\144\145\163\143\162\151\160\164\151\157\156", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xf9ffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[26];
static private final int[] jjstateSet = new int[52];
static protected char curChar;
/** Constructor. */
public SyntaxCheckerTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public SyntaxCheckerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 26; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2400L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
